name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🛠️ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🏗️ Build project
      run: |
        npm run build
        cp debug.txt dist/
        mv dist max-testing
        echo "Prepared max-testing folder content:"
        ls -R max-testing/

    - name: 🚀 Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        server: ${{ secrets.SFTP_SERVER }}
        port: 22
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: max-testing/
        remote_path: /home/smarter-choices-wellness/htdocs/wellness.smarter-choices.com/
        delete_remote_files: false
